#!/bin/bash

set -e

if [ -z "${GV_BINDIR}" ] || [ -z "${GV_CACHEDIR}" ]; then
	echo "GV_BINDIR or GV_CACHEDIR is not set" >&2
	echo "Please run this script via gvgit" >&2
	exit 1
fi

COMMITFILE=$(mktemp -p "${GNUPGHOME}")
cat - > "${COMMITFILE}"

KEY_ARGS=()

while read -r; do
	case ${REPLY} in
		committer*)
			EMAIL=${REPLY##*<}
			EMAIL=${EMAIL%%>*}
			while read -r KEY; do
				KEY_ARGS+=( --trusted-key "${KEY}" )
			done < <("${GV_BINDIR}"/gvgit-get-keyids "${GV_CACHEDIR}"/gentoo-devs.seeds "${EMAIL}")
			break
			;;
	esac
done < "${COMMITFILE}"

cat "${COMMITFILE}" | gpg "${KEY_ARGS[@]}" "${@}"
